// Webhook da Stripe: assinatura (a parte que decide quem pode ativar uma loja) e tradução dos eventos.
import fs from 'fs';
import crypto from 'crypto';
const src = fs.readFileSync('supabase/functions/webhook-stripe/index.ts', 'utf8');
const pega = (a, b) => src.slice(src.indexOf(`// <<${a}`), src.indexOf(`// ${b}>>`));
const { assinaturaValida, mapearEvento } = new Function('crypto', 'TextEncoder', pega('assinatura', 'assinatura') + '\n' + pega('mapa', 'mapa') + '\nreturn { assinaturaValida, mapearEvento };')(crypto.webcrypto, TextEncoder);
let ok = 0; const falhas = []; const t = (c, m) => (c ? ok++ : falhas.push(m));
const SEG = 'whsec_teste_segredo';
const assina = (corpo, seg = SEG, ts = 1791100000) => `t=${ts},v1=${crypto.createHmac('sha256', seg).update(`${ts}.${corpo}`).digest('hex')}`;
const corpo = '{"id":"evt_1abc","type":"invoice.paid"}';
const agora = 1791100000;
t(await assinaturaValida(corpo, assina(corpo), SEG, agora), 'assinatura correta é aceita');
t(!(await assinaturaValida(corpo, assina(corpo, 'outro_segredo'), SEG, agora)), 'assinatura feita com OUTRO segredo é recusada');
t(!(await assinaturaValida(corpo + ' ', assina(corpo), SEG, agora)), 'corpo alterado em 1 caractere é recusado');
t(!(await assinaturaValida(corpo, '', SEG, agora)) && !(await assinaturaValida(corpo, null, SEG, agora)), 'sem cabeçalho de assinatura é recusado');
t(!(await assinaturaValida(corpo, assina(corpo), '', agora)), 'SEM segredo configurado nada é aceito');
t(!(await assinaturaValida(corpo, assina(corpo), SEG, agora + 301)), 'pedido de mais de 5 minutos atrás (reenvio) é recusado');
t(await assinaturaValida(corpo, assina(corpo), SEG, agora + 299), 'dentro dos 5 minutos é aceito');
t(!(await assinaturaValida(corpo, assina(corpo), SEG, agora - 301)), 'relógio no futuro além da tolerância é recusado');
t(await assinaturaValida(corpo, `t=${agora},v1=deadbeef,v1=${assina(corpo).split('v1=')[1]}`, SEG, agora), 'Stripe pode mandar mais de uma assinatura (v1): basta uma válida');
t(!(await assinaturaValida(corpo, `t=${agora},v0=${assina(corpo).split('v1=')[1]}`, SEG, agora)), 'só assinatura v1 vale (v0 não)');
t(!(await assinaturaValida(corpo, 't=abc,v1=00', SEG, agora)) && !(await assinaturaValida(corpo, 'lixo', SEG, agora)), 'cabeçalhos malformados são recusados sem erro');
t(!(await assinaturaValida(corpo, `t=${agora},v1=${'0'.repeat(10)}`, SEG, agora)), 'assinatura de tamanho errado é recusada');

const ev = (type, obj) => ({ id: 'evt_x', type, data: { object: obj } });
let m = mapearEvento(ev('checkout.session.completed', { mode: 'subscription', payment_status: 'paid', client_reference_id: 'L1', metadata: { plano: 'inicio' }, customer: 'cus_1', subscription: 'sub_1' }));
t(m && m.loja_id === 'L1' && m.plano === 'inicio' && m.cliente === 'cus_1' && m.assinatura === 'sub_1', 'checkout pago vira compra com loja, plano, cliente e assinatura');
t(mapearEvento(ev('checkout.session.completed', { mode: 'payment', payment_status: 'paid' })) === null, 'checkout que não é assinatura é ignorado');
t(mapearEvento(ev('checkout.session.completed', { mode: 'subscription', payment_status: 'unpaid' })) === null, 'checkout NÃO pago ainda não ativa nada');
m = mapearEvento(ev('invoice.paid', { customer: 'cus_1', subscription: 'sub_1', lines: { data: [{ period: { end: 1793692800 } }] } }));
t(m && m.assinatura === 'sub_1' && m.proxima === '2026-11-03', 'fatura paga traz a próxima cobrança em data: ' + (m && m.proxima));
m = mapearEvento(ev('invoice.paid', { customer: 'cus_1', parent: { subscription_details: { subscription: 'sub_9' } }, lines: { data: [] } }));
t(m && m.assinatura === 'sub_9' && m.proxima === null, 'versão nova da API (assinatura dentro de parent) também funciona');
m = mapearEvento(ev('customer.subscription.updated', { id: 'sub_1', customer: 'cus_1', status: 'past_due', current_period_end: 1793692800 }));
t(m && m.status === 'past_due' && m.assinatura === 'sub_1', 'atualização de assinatura leva o estado da Stripe');
t(mapearEvento(ev('charge.refunded', { customer: 'c' })) === null, 'evento que não tratamos é ignorado');
t(mapearEvento({ type: 'invoice.paid' }) === null && mapearEvento(null) === null, 'evento sem dados não quebra');
console.log(falhas.length ? `STRIPE: ${falhas.length} FALHA(S)\n- ` + falhas.join('\n- ') : `STRIPE (assinatura e eventos) OK: ${ok} de ${ok}`);
process.exit(falhas.length ? 1 : 0);
