"""Roda todos os testes em navegador real: cadastro de produto (layout) + política de segurança."""
import sys
from pathlib import Path
sys.path.insert(0, str(Path(__file__).parent))
import editor, csp, login, suporte, painel_celular, lona_publica, lona_editor, lona_tema, romaneio, loja_online, maleta_acerto, ajuda, pagamento
falhas = editor.rodar(salvar_fotos=False)
print("\n--- política de segurança (BLOQUEANDO) ---")
ruim = csp.relatar(csp.rodar(csp.politica_completa()))
print("\n--- login ---")
ruim_login = login.rodar()
print("\n--- suporte da administradora ---")
ruim_suporte = suporte.rodar()
print("\n--- painel no celular: 4 larguras x 2 temas x 7 telas (contraste, toque, texto espremido) ---")
ruim_celular = painel_celular.rodar()
print("\n--- lona: vitrine pública da cliente (sem login) ---")
ruim_lona_pub = lona_publica.rodar()
print("\n--- lona: tela da dona e da consultora no app ---")
ruim_lona_ed = lona_editor.rodar()
print("\n--- lona no app: 3 larguras x 2 temas (contraste, toque, texto espremido) ---")
ruim_lona_tema = lona_tema.rodar()
print("\n--- loja on-line (antigo catálogo) ---")
ruim_loja = loja_online.rodar()
print("\n--- maleta: acerto completo (Equipe) ---")
ruim_maleta = maleta_acerto.rodar()
print("\n--- romaneio: preço, banho, pedra e foto na conferência + foto de peça existente ---")
ruim_romaneio = romaneio.rodar()
print("\n--- ajuda: botão no canto, busca, trilha de lições, mensagem do dia, acessibilidade ---")
ruim_ajuda = ajuda.rodar()
print("\n--- cobrança: teste vencido -> pagamento seguro (Stripe), volta do pagamento, carência, gerenciar assinatura ---")
ruim_pagamento = pagamento.rodar()
todos_ok = not (ruim_pagamento or ruim_ajuda or ruim_romaneio or ruim_loja or ruim_maleta or falhas or ruim or ruim_login or ruim_suporte or ruim_celular or ruim_lona_pub or ruim_lona_ed or ruim_lona_tema)
print("\nNAVEGADOR REAL: TUDO OK" if todos_ok else "\nNAVEGADOR REAL: HÁ PROBLEMAS")
sys.exit(0 if todos_ok else 1)
